"""
Developer 2 - Data Cleaner
Implements all cleaning and normalization rules for the manufacturing dataset.
"""

import re


# ---------------------------------------------------------------------------
# Timestamp normalisation helpers
# ---------------------------------------------------------------------------

# Patterns to parse the various formats generated by dataset_generator
_TS_PATTERNS = [
    # YYYY-MM-DD HH:MM
    re.compile(r"^(\d{4})-(\d{2})-(\d{2})\s+(\d{2}):(\d{2})$"),
    # DD/MM/YYYY HH:MM
    re.compile(r"^(\d{2})/(\d{2})/(\d{4})\s+(\d{2}):(\d{2})$"),
    # MM-DD-YYYY HH:MM
    re.compile(r"^(\d{2})-(\d{2})-(\d{4})\s+(\d{2}):(\d{2})$"),
    # YYYY/MM/DD HH:MM
    re.compile(r"^(\d{4})/(\d{2})/(\d{2})\s+(\d{2}):(\d{2})$"),
    # DD-MM-YYYY HH:MM
    re.compile(r"^(\d{2})-(\d{2})-(\d{4})\s+(\d{2}):(\d{2})$"),
]


def _parse_timestamp(ts_raw):
    """
    Attempt to parse the timestamp into (year, month, day, hour, minute).
    Returns None on failure.
    """
    ts = ts_raw.strip()

    # YYYY-MM-DD HH:MM  or  YYYY/MM/DD HH:MM
    m = re.match(r"^(\d{4})[-/](\d{2})[-/](\d{2})\s+(\d{2}):(\d{2})$", ts)
    if m:
        return int(m.group(1)), int(m.group(2)), int(m.group(3)), int(m.group(4)), int(m.group(5))

    # DD/MM/YYYY HH:MM  or  DD-MM-YYYY HH:MM
    m = re.match(r"^(\d{2})[/-](\d{2})[/-](\d{4})\s+(\d{2}):(\d{2})$", ts)
    if m:
        g1, g2, g3 = int(m.group(1)), int(m.group(2)), int(m.group(3))
        hour, minute = int(m.group(4)), int(m.group(5))
        # Heuristic: if first group > 12 it is a day (DD/MM/YYYY)
        if g1 > 12:
            return g3, g2, g1, hour, minute
        # If second group > 12 it is MM-DD-YYYY
        if g2 > 12:
            return g3, g1, g2, hour, minute
        # Ambiguous – default to DD/MM/YYYY
        return g3, g2, g1, hour, minute

    return None


def normalize_timestamp(ts_raw):
    """
    Normalise a timestamp string to 'YYYY-MM-DD HH:MM'.
    Fixes invalid minutes (>59) by clamping to 59.
    Returns (normalised_string, is_valid).
    """
    parsed = _parse_timestamp(ts_raw)
    if parsed is None:
        return ts_raw, False

    year, month, day, hour, minute = parsed

    # Fix minutes that exceed 59
    if minute > 59:
        minute = 59

    # Basic sanity checks
    if not (1 <= month <= 12 and 1 <= day <= 31 and 0 <= hour <= 23):
        return ts_raw, False

    normalised = f"{year:04d}-{month:02d}-{day:02d} {hour:02d}:{minute:02d}"
    return normalised, True


# ---------------------------------------------------------------------------
# Field-level cleaners
# ---------------------------------------------------------------------------

def clean_line(value):
    """Trim spaces, convert to uppercase."""
    return value.strip().upper()


def clean_station(value):
    """Trim spaces, convert to uppercase."""
    return value.strip().upper()


def clean_part_number(value):
    """Uppercase, ensure hyphen between prefix and numeric part."""
    pn = value.strip().upper()
    # If there is a space instead of hyphen, replace it
    pn = re.sub(r"\s+", "-", pn)
    # If prefix and digits are not separated by hyphen, insert one
    m = re.match(r"^([A-Z]+)(\d+)$", pn)
    if m:
        pn = f"{m.group(1)}-{m.group(2)}"
    return pn


def clean_torque(value):
    """Extract numeric torque value in Nm."""
    raw = value.strip().upper().replace("NM", "").strip()
    try:
        return round(float(raw), 2)
    except ValueError:
        return None


def clean_temperature(value):
    """Convert temperature to Celsius. Handles 'C' and 'F' suffixes."""
    raw = value.strip().upper()
    if raw.endswith("F"):
        try:
            f_val = float(raw[:-1])
            return round((f_val - 32) * 5 / 9, 2)
        except ValueError:
            return None
    elif raw.endswith("C"):
        try:
            return round(float(raw[:-1]), 2)
        except ValueError:
            return None
    else:
        try:
            return round(float(raw), 2)
        except ValueError:
            return None


def clean_defect(value):
    """Normalise defect values: na/OK/None/'' -> None; Reject/Repair kept."""
    raw = value.strip().lower()
    if raw in ("na", "ok", "none", "n/a", ""):
        return ""
    if "reject" in raw:
        return "Reject"
    if "repair" in raw:
        return "Repair"
    return value.strip()


def clean_vin(value):
    """Remove spaces, convert to uppercase."""
    return value.replace(" ", "").strip().upper()


def clean_supplier(value):
    """Uppercase and trim."""
    return value.strip().upper()


# ---------------------------------------------------------------------------
# Row-level cleaner
# ---------------------------------------------------------------------------

def clean_row(row):
    """
    Apply all cleaning rules to a single row dict.
    Returns the cleaned row and a list of issues found.
    """
    issues = []
    cleaned = dict(row)

    # Line & Station
    cleaned["Line"] = clean_line(row.get("Line", ""))
    cleaned["Station"] = clean_station(row.get("Station", ""))

    # Timestamp
    ts_norm, ts_valid = normalize_timestamp(row.get("TS", ""))
    cleaned["TS"] = ts_norm
    if not ts_valid:
        issues.append("invalid_timestamp")

    # Part number
    cleaned["Part_No"] = clean_part_number(row.get("Part_No", ""))

    # Torque
    torque_val = clean_torque(row.get("Torque", ""))
    if torque_val is None:
        issues.append("invalid_torque")
        cleaned["Torque_Nm"] = ""
    else:
        cleaned["Torque_Nm"] = torque_val
    # Remove old column, keep new
    cleaned.pop("Torque", None)

    # Temperature -> Celsius
    temp_val = clean_temperature(row.get("Temp", ""))
    if temp_val is None:
        issues.append("invalid_temperature")
        cleaned["Temp_C"] = ""
    else:
        cleaned["Temp_C"] = temp_val
    cleaned.pop("Temp", None)

    # Defect
    cleaned["Defect"] = clean_defect(row.get("Defect", ""))

    # VIN
    cleaned["VIN"] = clean_vin(row.get("VIN", ""))

    # Supplier
    cleaned["Supplier"] = clean_supplier(row.get("Supplier", ""))

    return cleaned, issues


def clean_dataset(rows):
    """
    Clean the full dataset.
    Returns (cleaned_rows, issue_log) where issue_log is a list of
    (Event_ID, issues) tuples.
    """
    cleaned_rows = []
    issue_log = []
    for row in rows:
        cleaned, issues = clean_row(row)
        cleaned_rows.append(cleaned)
        if issues:
            issue_log.append((row.get("Event_ID", "?"), issues))

    print(f"[Cleaner] Cleaned {len(cleaned_rows)} records, {len(issue_log)} had issues")
    return cleaned_rows, issue_log
